version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-server   

  node-server:
    build: .
    volumes:
     - ./:/app
     - /app/node_modules 
    environment:
      - PORT=3000
      - MONGO_USER=root
      - MONGO_PASSWORD=password123
    depends_on:
      - mongodb
      - rabbitmq

  rabbitmq:
    image: rabbitmq:latest

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
